#!/usr/bin/env python3
"""Generate webapp/words.js from open word-list sources.

Each locale gets two pools:

* ``answers``  — the curated common-noun pool the daily word is drawn from.
  These are kept as the source of truth: they are read back from the existing
  ``webapp/words.js`` (so the curated nouns are never lost on regeneration).
* ``accepted`` — a large dictionary of valid 5-letter words used ONLY to
  validate guesses (a guess must be in this set). It is the union of a filtered
  external word list and the ``answers`` (so every answer is always guessable).

Sources (downloaded once into ``tools/_cache/`` if not already present):

* en: dwyl/english-words ``words_alpha.txt`` — Unlicense (public domain).
* ru/uk: hermitdave/FrequencyWords ``*_50k.txt`` (OpenSubtitles 2018 top-50k,
  i.e. common words) — CC BY-SA 4.0. See NOTICE.md.

Run:  python tools/build_words.py
"""

from __future__ import annotations

import re
import ssl
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORDS_JS = ROOT / "webapp" / "words.js"
CACHE = Path(__file__).resolve().parent / "_cache"

SOURCES = {
    "en": "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt",
    "ru": "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/ru/ru_50k.txt",
    "uk": "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/uk/uk_50k.txt",
}

ALPHABETS = {
    "ru": set("абвгдежзийклмнопрстуфхцчшщъыьэюя"),
    "uk": set("абвгґдеєжзиіїйклмнопрстуфхцчшщьюя"),
    "en": set("abcdefghijklmnopqrstuvwxyz"),
}


def fetch(lang: str) -> str:
    """Return the raw source text, using a cached copy when available."""
    CACHE.mkdir(exist_ok=True)
    cached = CACHE / f"{lang}.txt"
    if cached.exists():
        return cached.read_text(encoding="utf-8", errors="ignore")
    url = SOURCES[lang]
    print(f"downloading {lang}: {url}")
    try:
        ctx = ssl.create_default_context()
        with urllib.request.urlopen(url, context=ctx, timeout=120) as resp:
            data = resp.read().decode("utf-8", errors="ignore")
    except Exception as exc:  # noqa: BLE001
        raise SystemExit(
            f"failed to download {lang} ({exc}). Pre-download it to {cached} and re-run."
        ) from exc
    cached.write_text(data, encoding="utf-8")
    return data


def filtered_words(lang: str, text: str) -> set[str]:
    alphabet = ALPHABETS[lang]
    words: set[str] = set()
    for line in text.splitlines():
        token = line.split()[0] if line.split() else ""
        token = token.strip().lower()
        if lang == "ru":
            token = token.replace("ё", "е")
        if len(token) == 5 and set(token) <= alphabet:
            words.add(token)
    return words


def read_answers() -> dict[str, list[str]]:
    """Extract the curated ``answers`` per locale from the current words.js."""
    text = WORDS_JS.read_text(encoding="utf-8")
    answers: dict[str, list[str]] = {}
    keys = list(re.finditer(r"^  (ru|uk|en):", text, re.M))
    for i, m in enumerate(keys):
        lang = m.group(1)
        block = text[m.end() : keys[i + 1].start() if i + 1 < len(keys) else len(text)]
        arr = re.search(r"answers\s*:\s*\[(.*?)\]", block, re.S) or re.search(
            r"\[(.*?)\]", block, re.S
        )
        answers[lang] = re.findall(r'"([^"]+)"', arr.group(1)) if arr else []
    return answers


def render_array(words: list[str], indent: str, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(words), per_line):
        chunk = ", ".join(f'"{w}"' for w in words[i : i + per_line])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def main() -> None:
    answers = read_answers()
    blocks = []
    for lang in ("ru", "uk", "en"):
        ans = answers.get(lang, [])
        accepted = sorted(filtered_words(lang, fetch(lang)) | set(ans))
        print(f"{lang}: answers={len(ans)} accepted={len(accepted)}")
        blocks.append(
            f"  {lang}: {{\n"
            f"    answers: [\n{render_array(ans, '      ')}\n    ],\n"
            f"    accepted: [\n{render_array(accepted, '      ')}\n    ],\n"
            f"  }},"
        )
    header = (
        "/*\n"
        " * Daily-word pools for the engine, one entry per locale, GENERATED by\n"
        " * tools/build_words.py — do not edit by hand.\n"
        " *\n"
        " *   answers  — curated common-noun pool the daily word is drawn from.\n"
        " *   accepted — large dictionary of valid 5-letter words; a guess is only\n"
        " *              accepted if it is in this set (answers are always included).\n"
        " *\n"
        " * Word data: en from dwyl/english-words (Unlicense); ru/uk from\n"
        " * hermitdave/FrequencyWords (CC BY-SA 4.0). See NOTICE.md. Engine code is MIT.\n"
        " */\n"
    )
    body = "window.VERBA_WORDS = {\n" + "\n".join(blocks) + "\n};\n"
    WORDS_JS.write_text(header + body, encoding="utf-8")
    print(f"wrote {WORDS_JS}")


if __name__ == "__main__":
    sys.exit(main())
